INSERT INTO Bibliotheque.Contenus
VALUES
(1000, 'Le Seigneur des Anneaux', 'J.R.R. Tolkien', 'Livre', 'Fantasy'),
(1001, 'Jurassic Park', 'Michael Crichton', 'Livre', 'Science-fiction'),
(1002, 'Inception', 'Christopher Nolan', 'Film', 'Science-fiction'),
(1003, 'The Beatles Anthology', 'The Beatles', 'Album', 'Rock'),
(1004, '1984', 'George Orwell', 'Livre', 'Dystopie'),
(1005, 'La La Land', 'Damien Chazelle', 'Film', 'Romance'),
(1006, 'Thriller', 'Michael Jackson', 'Album', 'Pop'),
(1007, 'National Geographic', 'National Geographic Society', 'Magazine', 'Science'),
(1008, "Harry Potter à l'école des sorciers", 'J.K. Rowling', 'Livre', 'Fantasy'),
(1009, 'The Shawshank Redemption', 'Frank Darabont', 'Film', 'Drame'),
(1010, 'The Dark Side of the Moon', 'Pink Floyd', 'Album', 'Rock'),
(1011, 'The Godfather', 'Francis Ford Coppola', 'Film', 'Drame'),
(1012, 'The Godfather', 'Mario Puzo', 'Livre', 'Drame'),
(1013, 'The Godfather Part II', 'Francis Ford Coppola', 'Film', 'Drame'),
(1014, 'The Godfather Part II', 'Mario Puzo', 'Livre', 'Drame'),
(1015, 'The Godfather Part III', 'Francis Ford Coppola', 'Film', 'Drame'),
(1016, 'The Godfather Part III', 'Mario Puzo', 'Livre', 'Drame'),
(1017, 'The Dark Knight', 'Christopher Nolan', 'Film', 'Drame'),
(1018, 'The Dark Knight', 'Christopher Nolan', 'Livre', 'Drame'),
(1019, 'The Dark Knight Rises', 'Christopher Nolan', 'Film', 'Drame'),
(1020, 'The Dark Knight Rises', 'Christopher Nolan', 'Livre', 'Drame'),
(1021, 'Les Misérables', 'Victor Hugo', 'Livre', 'Drame'),
(1022, 'Amélie Poulain', 'Jean-Pierre Jeunet', 'Film', 'Comédie'),
(1023, 'Blade Runner', 'Ridley Scott', 'Film', 'Science-fiction'),
(1024, 'Les Fleurs du Mal', 'Charles Baudelaire', 'Livre', 'Poésie'),
(1025, 'Le Voyage dans la Lune', 'Georges Méliès', 'Film', 'Science-fiction'),
(1026, 'La Guerre des Étoiles', 'George Lucas', 'Film', 'Science-fiction'),
(1027, 'MadMax: Fury Road', 'George Miller', 'Film', 'Science-fiction'),
(1028, 'Le Petit Prince', 'Antoine de Saint-Exupéry', 'Livre', 'Fantasy'),
(1029, "Le Fabuleux Destin d\'Amélie Poulain", 'Yann Tiersen', 'Album', 'Musique de film'),
(1030, 'Le Hobbit', 'J.R.R. Tolkien', 'Livre', 'Fantasy'),
(1031, 'Blade Runner', 'Philip K. Dick', 'Livre', 'Science-fiction'),
(1032, 'Abbey Road', 'The Beatles', 'Album', 'Rock'),
(1033, 'The Catcher in the Rye', 'J.D. Salinger', 'Livre', 'Fiction'),
(1034, 'The Godfather', 'Francis Ford Coppola', 'Film', 'Crime'),
(1035, 'Kind of Blue', 'Miles Davis', 'Album', 'Jazz'),
(1036, 'Time', 'National Geographic Society', 'Magazine', 'Science'),
(1037, 'To Kill a Mockingbird', 'Harper Lee', 'Livre', 'Drame'),
(1038, 'Pulp Fiction', 'Quentin Tarantino', 'Film', 'Thriller'),
(1039, 'The Wall', 'Pink Floyd', 'Album', 'Rock'),
(1040, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Livre', 'Romance');